filebeat.inputs:
  - type: filestream
    paths:
      - "/var/logs/my-experiment/**/*.jsonl"
    index: experiment-logs

setup.ilm.enabled: false
setup.template:
  enabled: true
  overwrite: true
  name: experiment-logs
  pattern: experiment-logs*
  settings.index:
    number_of_replicas: 0
    data_stream: {}

output.elasticsearch:
  hosts: ${ELASTIC_HOST}
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}
  non_indexable_policy.dead_letter_index:
    index: "bad-experiment-logs"
