metricbeat.modules:
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "event"
      - "healthcheck"
      - "info"
      - "memory"
      - "network"
    hosts: [ "unix:///var/run/docker.sock" ]
    period: 10s

  - module: system
    metricsets:
      - cpu # CPU usage
      - load # CPU load averages
      - memory # Memory usage
      - network # Network IO
      - process # Per process metrics
      - process_summary # Process summary
      - uptime # System Uptime
      - socket_summary # Socket summary
      - core # Per CPU core usage
      - filesystem # File system usage for each mountpoint
    enabled: true
    period: 5s
    processes: [ ".*" ]

    # Mount point of the host’s filesystem 
    hostfs: "/hostfs"
    cpu.metrics: [ "percentages", "normalized_percentages" ]
    core.metrics: [ "percentages" ]

# Used for setting up metrics dashboards
setup.kibana.host: http://kibana:5601

setup.ilm.enabled: true
setup.template:
  enabled: true
  settings.index.number_of_replicas: 0

output.elasticsearch:
  hosts: ${ELASTIC_HOST}
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}
